nome = input('qual seu nome?')
print ('prazer tem te conhecer {:>20}!'.format(nome))
print ('prazer tem te conhecer {:<20}!'.format(nome))
print ('prazer em te conhecer {:^20}!'.format(nome))
print ('prazer em te conhecer {:=^20}!'.format(nome))